# Generated by Django 4.0.5 on 2022-06-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_status',
        ),
    ]
